derdour/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', views.home, name='home'),
    path('', include('jobs.urls')),
    path('accounts/', include('accounts.urls')),
    # path('accounts/', include('accounts.urls')),
    # path('jobs/', include('jobs.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jobs/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.home, name='home'),
    path('jobs', views.jobs, name='jobs'),
    path('show_CVs', views.show_CVs, name='show_CVs'),
    path('hiring', views.hiring, name='hiring'),
    path('drop_CV', views.drop_CV, name='drop_CV'),
    path('<int:job_id>', views.detail, name='detail'),
    path('<int:job_id>/add_like', views.add_like, name='add_like'),
    path('contact', views.contact, name='contact'),
    # path('search', views.search, name='search'),
    path('favorites', views.favorites, name='favorites'),
    path('CV/<int:CV_id>', views.detail_CV, name='detail_CV'),
    path('<int:job_id>/apply', views.apply, name='apply'),
    path('admin_dashboard', views.admin_dashboard, name='admin_dashboard'),
] +  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

jobs/models.py
from django.db import models
from django.contrib.auth.models import User

JOBS_CHOICES = [
    ('Reception', (
        (11, 'Réceptionniste'), (12, 'Chef de réception'),
    )),
    ('Salle', (
        (21, 'Maître d\'hôtel'), (22, 'Serveur(se)'), (23, 'Sommelier'), (24, 'Barman'),
    )),
    ('Entretien', (
        (31, 'Femme de chambre'), (32, 'Maçon'), (33, 'Plombier'), (34, 'Electricien'),
    )),
    ('Restauration', (
        (41, 'Cuisinier'), (42, 'Chef de cuisine'), (43, 'Patissier'),
    )),
    ('Sécurité', (
        (51, 'Agent de sécurité'), (52, 'Chef de sécurité'), (53, 'Spécialiste caméras'),
    )),
]

JOBS_TYPES = [
    ('CDI', 'CDI'), ('CDD', 'CDD'), ('SAIS', 'Saisonier'),
]


class Job(models.Model):

    title = models.TextField()
    company = models.TextField()
    location = models.TextField()
    salary = models.TextField()
    link = models.URLField()
    category = models.IntegerField(choices=JOBS_CHOICES)
    contract_type = models.CharField(max_length=4, choices=JOBS_TYPES)
    description = models.TextField(blank=True)
    job_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    def summary_of_description(self):
        desc = self.description
        if len(desc) > 130:
            return desc[:130]+"..."
        return desc


class CV(models.Model):

    picture = models.ImageField(upload_to='media/')
    firstname = models.TextField()
    lastname = models.TextField()
    email = models.TextField()
    location = models.TextField()
    category = models.IntegerField(choices=JOBS_CHOICES)
    description = models.TextField()
    cv_file = models.FileField(upload_to='media/')
    registration_date = models.DateTimeField(auto_now_add=True)
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.firstname + self.lastname.upper()

    def pretty_date(self):
        return self.registration_date.strftime("%d/%m/%Y")


class Likes(models.Model):
    user_id   = models.ForeignKey(User, on_delete=models.CASCADE)
    job_id    = models.ForeignKey(Job,  on_delete=models.CASCADE)
    like_date = models.DateTimeField(auto_now_add=True)


class Comments(models.Model):
    user_id   = models.ForeignKey(User, on_delete=models.CASCADE)
    job_id    = models.ForeignKey(Job,  on_delete=models.CASCADE)
    comment_date = models.DateTimeField(auto_now_add=True)
    comment  = models.TextField()

    def pretty_date(self):
        return self.comment_date.strftime("%Y-%m-%d %H:%M")


class Applications(models.Model):
    user_id   = models.ForeignKey(User, on_delete=models.CASCADE)
    job_id    = models.ForeignKey(Job,  on_delete=models.CASCADE)
    app_date = models.DateTimeField(auto_now_add=True)

jobs/views.py
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.postgres.search import *
from .models import *


def home(request):
    return render(request, 'jobs/home.html', {'jobs_count': Job.objects.count()})


def contact(request):
    return render(request, 'jobs/contact.html')


def jobs(request):
    jobs = Job.objects.all()
    return render(request, 'jobs/jobs.html', {'jobs': jobs,
                                              'jobs_count': Job.objects.count()})


def show_CVs(request):
    CVs = CV.objects.all()
    return render(request, 'jobs/show_CVs.html', {'CVs': CVs,
                                                  'CVs_count': CV.objects.count()})


@login_required(login_url="/accounts/login")
def hiring(request):
    if request.method == 'POST':
        print("JJJJJJJJJJJJJJJJJJ")
        job = Job.objects.create(
            title= request.POST["title"],
            company= request.POST["company"],
            location= request.POST["location"],
            salary= request.POST["salary"],
            link= request.POST["link"],
            category= request.POST["category"],
            contract_type= request.POST["contract_type"],
            description= request.POST["description"]
        )
        job.save()
        return render(request, 'jobs/hiring.html', {'success': 'Annonce créée avec succés !'})
    else:
        return render(request, 'jobs/hiring.html')


@login_required(login_url="/accounts/login")
def drop_CV(request):
    if request.method == 'POST':

        cv_file = CV.objects.create(
            picture= request.POST["picture"],
            firstname= request.POST["firstname"].capitalize(),
            lastname= request.POST["lastname"].upper(),
            email= request.POST["email"].lower(),
            location= request.POST["location"].capitalize(),
            category= request.POST["category"],
            description= request.POST["description"],
            cv_file= request.POST["cv_file"],
            user_id= request.user,
        )
        cv_file.save()
        return render(request, 'jobs/drop_CV.html', {'success': 'Votre CV a été déposé avec succés !'})
    else:
        return render(request, 'jobs/drop_CV.html')


def detail(request, job_id):
    job = get_object_or_404(Job, pk=job_id)
    job_likes_count = Likes.objects.filter(job_id=job_id).count()
    job_comments = Comments.objects.filter(job_id=job_id)

    exists_app = Applications.objects.filter(job_id=job_id, user_id=request.user.id).exists()

    return render(request, 'jobs/detail.html',
                  {'job': job, 'likes_count': job_likes_count, 'job_comments': job_comments, "already_exists": exists_app})


def add_action(request, job_likes, job_id):
    if job_likes.filter(user_id=request.user.id, job_id=job_id).exists():
        job_likes.filter(user_id=request.user, job_id=get_object_or_404(Job, pk=job_id)).delete()
    else:
        job_likes.create(user_id=request.user, job_id=get_object_or_404(Job, pk=job_id))


@login_required(login_url="/accounts/login")
def add_like(request, job_id):
    if request.method == 'POST':
        job_likes = Likes.objects.all()
        add_action(request, job_likes, job_id)
        return redirect('/' + str(job_id))


@login_required(login_url="/accounts/login")
def favorites(request):
    pks = Likes.objects.all().filter(user_id=request.user.id)
    pks = [job.job_id for job in pks]
    liked_jobs = Job.objects.filter(title__in=list(pks)).all()
    jobs_count = len(liked_jobs)
    # liked_jobs = Job.objects.filter(pk__in=Likes.objects.filter(user_id=request.user.id))

    return render(request, 'jobs/jobs.html', {'jobs': liked_jobs,
                                              'jobs_count': jobs_count})


def detail_CV(request, CV_id):
    cv = get_object_or_404(CV, pk=CV_id)
    associated_jobs = Job.objects.filter(category=cv.category)

    return render(request, 'jobs/detail_CV.html', {'cv': cv, "jobs": associated_jobs, "jobs_count": associated_jobs.count()})


@login_required(login_url="/accounts/login")
def apply(request, job_id):
    if request.method == 'POST':
        try:
            job_app = Applications.objects.get(job_id=job_id, user_id = request.user)
            return redirect('/' + str(job_id))
        except Applications.DoesNotExist:
            job = Job.objects.get(pk=job_id)
            job_app = Applications.objects.create(job_id=job, user_id = request.user)
            job_app.save()
            return redirect('/' + str(job_id))


@login_required(login_url="/accounts/login")
def admin_dashboard(request):
    jobs = Job.objects.all()
    jobs_apps_dict = {}
    for job in jobs:
        ass_apps = Applications.objects.filter(job_id=job.pk)
        ass_users_idx = [app.user_id for app in ass_apps]
        jobs_apps_dict[job] = CV.objects.filter(user_id__in=ass_users_idx)

    return render(request, 'jobs/admin_dashboard.html', {'jobs_apps_dict': jobs_apps_dict, "jobs_count": len(jobs_apps_dict)})

jobs/templates/jobs/admin_dashboard.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


    <h1 align="center">Offres et candidature ({{ jobs_count }} offres):</h1>

    <br>
    {% for job, associated_users in jobs_apps_dict.items %}
        <div class="row" style="min-height: 200px">
            <div class="col-lg-2" style="align-self: center;text-align: center;cursor: pointer;" onclick="window.location='{% url 'detail' job.id %}';">
                <p>{{ job.title }}</p>
                <p>{{ job.company }}</p>
            </div>
            <div class="col-lg-10">
                <div class="scrollhor" style="min-height: 200px">
                    {% if associated_users.count == 0 %}
                        <h2 align="center">Désolé, aucune candidature pour ce poste !</h2>
                    {% endif %}
                    {% for user in associated_users %}
                        <div class="card  home-card border-warning col-sm-4 col-md-3 col-lg-2">
                            <div class="card-body pb0 " onclick="window.location='{% url 'detail_CV' user.id %}';" style="cursor: pointer;">
                                <p>{{ user.firstname.capitalize }} {{ user.lastname.upper }}</p>
                                <p><span class="oi oi-box"></span> {{ user.email }}</p>
                                <p><span class="oi oi-location"></span> {{ user.location }}</p>
                                <p><span class="oi oi-wrench"></span> {{ user.get_category_display }}</p>
                                <p></p>
                            </div>

                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    {% endfor %}






    <div class="jobs">
        <div class="row">
            {% for job in jobs %}
                <div class="card border-warning col-sm-6 col-md-4 col-lg-3 job-card">
                    <img src="{% static 'hotel_staff.jpg' %}" class="card-img-top" onclick="window.location='{% url 'detail' job.id %}';" style="cursor: pointer;">
                    <div class="card-body pb0">
                        <h5 class="card-title" onclick="window.location='{% url 'detail' job.id %}';" style="cursor: pointer;">{{ job.title }}</h5>
                        <h5>{{ job.company }}</h5>
                        <hr width="90%">
                        <p class="card-text pt0"><small>{{ job.summary_of_description }}</small></p>
                    </div>
                    <div class="card-footer border-warning bt0">
                        <table class="table table-bordered">
                            <tbody>
                            <tr>
                                <th><small>{{ job.salary }}DA</small> </th>
                                <th><small>{{ job.get_category_display }}</small></th>
                                <th><small>{{ job.get_contract_type_display }}</small></th>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>




{% endblock %}

jobs/templates/jobs/contact.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <div class="row">
        <div class="col-lg-7">
            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1145.186326863465!2d-0.5919990326658846!3d35.724347654397505!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0xd7e62a4a37db9b5%3A0x73cf55b9004b3b71!2sDN%20Vetment!5e0!3m2!1sfr!2sfr!4v1622023347269!5m2!1sfr!2sfr" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
        </div>
        <div class="col-lg-5">
            <br>
            <br>
            <p>
                CRH<br>
                Rue Dubaï, Bir El Djir, Oran, Algérie
            <br>
            <br>
            <br>
                CHR Recrutement <br>
                rachidderdour20@gmail.com <br>
                06 66 66 66 66
            </p>

        </div>

    </div>



    <br><br><br>











    {#<div class="row">#}
    {#  <div class="col-lg-2">#}
    {#    <img src="https://image.ibb.co/jw55Ex/def_face.jpg" class="img img-rounded img-fluid" style="height: 105px;"/>#}
    {#  </div>#}
    {#  <div class="col-lg-10">#}
    {#    <p>#}
    {#      <strong>Maniruzzaman Akash</strong>#}
    {#      <span class="text-secondary text-right">15 Minutes Ago</span>#}
    {#    </p>#}
    {#    <p>Lorem Ipsum is simply dummy text of the pr make  but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>#}
    {#  </div>#}
    {#</div>#}
    {##}
    {##}
    {#<br><br>#}
    {##}
    {#<div class="comment mt-4 text-justify float-left"> <img src="https://i.imgur.com/yTFUilP.jpg" alt="" class="rounded-circle" width="40" height="40">#}
    {#  <h4>Jhon Doe</h4> <span>- 20 October, 2018</span> <br>#}
    {#  <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Accusamus numquam assumenda hic aliquam vero sequi velit molestias doloremque molestiae dicta?</p>#}
    {#</div>#}
    {#<div class="text-justify darker mt-4 float-right"> <img src="https://i.imgur.com/CFpa3nK.jpg" alt="" class="rounded-circle" width="40" height="40">#}
    {#  <h4>Rob Simpson</h4> <span>- 20 October, 2018</span> <br>#}
    {#  <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Accusamus numquam assumenda hic aliquam vero sequi velit molestias doloremque molestiae dicta?</p>#}
    {#</div>#}
    {##}
    {#<div class="toast" role="alert" aria-live="assertive" aria-atomic="true">#}
    {#  <div class="toast-header">#}
    {#    <img src="..." class="rounded me-2" alt="...">#}
    {#    <strong class="me-auto">Bootstrap</strong>#}
    {#    <small>11 mins ago</small>#}
    {#    <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>#}
    {#  </div>#}
    {#  <div class="toast-body">#}
    {#    Hello, world! This is a toast message.#}
    {#  </div>#}
    {#</div>#}
    {##}
    {#<div class="toast" role="alert" aria-live="assertive" aria-atomic="true">#}
    {#  <div class="toast-header">#}
    {#    <strong class="me-auto">Bootstrap</strong>#}
    {#    <small class="text-muted">11 mins ago</small>#}
    {#    <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>#}
    {#  </div>#}
    {#  <div class="toast-body">#}
    {#    Hello, world! This is a toast message.#}
    {#  </div>#}
    {#</div>#}

    {##}
    {#<h1>Our selections for you:</h1>#}
    {#{% for cluster_num, suggested_recipes in clusters.items %}#}
    {#<h2>Selection {{ cluster_num }}</h2>#}
    {#<div class="scrollhor">#}
    {#  {% for recipe in suggested_recipes %}#}
    {##}
    {#  <div class="card border-warning col-sm-4 col-md-3 col-lg-2">#}
    {#    <img src="{{ recipe.image }}" class="card-img-top" onclick="window.location='{% url 'detail' recipe.id %}';" style="cursor: pointer;">#}
    {#    <div class="card-body pb0 card-body-home">#}
    {#      <h5 class="card-title" onclick="window.location='{% url 'detail' recipe.id %}';" style="cursor: pointer;"><small> {{ recipe.title }}</small></h5>#}
    {#    </div>#}
    {#  </div>#}
    {#  {% endfor %}#}
    {#</div>#}
    {#{% endfor %}#}
    {##}
    {##}
    {##}
    {##}
    {##}
    {#<h5>Today's special</h5>#}
    {##}
    {#<div class="card flex-row flex-wrap">#}
    {#  <div class="card-header border-0">#}
    {#    <img src="{{ todays_special.image }}" width="200" class="card-img-top" onclick="window.location='{% url 'detail' todays_special.id %}';" style="cursor: pointer;">#}
    {#  </div>#}
    {#  <div class="card-block px-2">#}
    {#    <h4 class="card-title" onclick="window.location='{% url 'detail' todays_special.id %}';" style="cursor: pointer;">{{ todays_special.title }}</h4>#}
    {#    <p class="card-text">{{ todays_special.summary }}</p>#}
    {#  </div>#}
    {#  <div class="w-100"></div>#}
    {#  <div class="card-footer w-100 text-muted">#}
    {#    <span><span class="oi oi-clock"></span> {{ todays_special.ready_in_minutes }}min / </span>#}
    {#    <span> {{ todays_special.price_per_serving }}$</span>#}
    {#  </div>#}
    {#</div>#}
    {##}
    {#<br>#}
    {#<!--<br>-->#}
    {#<!--<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Did you know that Interior is responsible for the development of renewable energy resources on the Outer Continental Shelf? To learn more about the lifecycle of offshore renewable energy visit: <a href="https://t.co/otuk0nyiry">https://t.co/otuk0nyiry</a> <a href="https://t.co/y28WovdaKy">pic.twitter.com/y28WovdaKy</a></p>&mdash; US Department of the Interior (@Interior) <a href="https://twitter.com/Interior/status/1375106996823805953?ref_src=twsrc%5Etfw">March 25, 2021</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>-->#}
    {#<!--<br>-->#}
    {#<br>#}
    {##}
    {##}
    {##}
    {#<br>#}
    {##}
    {##}
    {##}
    {##}
    {#<div class="row">#}
    {#  {% for recipe in recipes %}#}
    {#  <div class="card border-warning col-sm-12 col-md-6 col-lg-4">#}
    {#    <img src="{{ recipe.image }}" class="card-img-top" onclick="window.location='{% url 'detail' recipe.id %}';" style="cursor: pointer;">#}
    {#    <div class="card-body pb0">#}
    {#      <h5 class="card-title" onclick="window.location='{% url 'detail' recipe.id %}';" style="cursor: pointer;">{{ recipe.title }}</h5>#}
    {#      <hr width="90%">#}
    {#      <p class="card-text pt0"><small>{{ recipe.summary_of_summary }}</small></p>#}
    {#    </div>#}
    {#    <div class="card-footer border-warning bt0">#}
    {#      <span><span class="oi oi-clock"></span> {{ recipe.ready_in_minutes }}min / </span>#}
    {#      <span> {{ recipe.price_per_serving }}$</span>#}
    {#    </div>#}
    {#  </div>#}
    {#  {% endfor %}#}
    {#</div>#}





{% endblock %}

jobs/templates/jobs/detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <h3>{{ job.title }}</h3>



    <div class="row mt6">
        <div class="col-6">
            <img src="{% static 'hotel_staff.jpg' %}" class="img-fluid" />
        </div>
        <div class="col-6">
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th><span class="oi oi-home"></span> {{ job.company }}</th>
                    <th><span class="oi oi-location"></span> {{ job.location }}</th>
                </tr>
                </thead>
            </table>
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th><span class="oi oi-euro"></span> {{ job.salary }} D.A</th>
                    <th><span class="oi oi-wrench"></span> {{ job.get_category_display }}</th>
                    <th><span class="oi oi-target"></span> {{ job.get_contract_type_display }}</th>
                </tr>
                </thead>
            </table>

            <button type="button" class="btn btn-success" style="width: inherit;">
                <a href="javascript:{document.getElementById('add_like').submit()}" style="color: white;"><span class="badge rounded-pill bg-success"><span class="oi oi-thumb-up"></span>Like ({{ likes_count }})</span></a>
            </button>
            <br><br>
            {% if not already_exists %}
            <button type="button" class="btn btn-warning" style="width: inherit;">
                <a href="javascript:{document.getElementById('apply').submit()}" style="color: white;"><span class="badge rounded-pill bg-warning"> Postuler</span></a>
            </button>
            {% else %}
            <button type="button" class="btn btn-secondary" style="width: inherit;" disabled>
                <a style="color: white;"><span class="badge rounded-pill bg-secondary"> Vous avez déja postulé à cette offre !</span></a>
            </button>
            {% endif %}
            <br><br>
            <h3>Description du poste:</h3>
            <p> {{ job.description }} </p>
            <br>

        </div>
    </div>





    <hr width="80%">










    <form id="add_like" method="POST" action="{% url 'add_like' job.id %}">
      {% csrf_token%}
      <input type="hidden">
    </form>

    <form id="apply" method="POST" action="{% url 'apply' job.id %}">
      {% csrf_token%}
      <input type="hidden">
    </form>



{% endblock %}

jobs/templates/jobs/detail_CV.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <h3>{{ cv.firstname.capitalize }} {{ cv.lastname.upper }}</h3>

    {#    email = models.TextField()#}
    {#    category = models.IntegerField(choices=JOBS_CHOICES)#}
    {#    registration_date = models.DateTimeField(auto_now_add=True)#}

    <div class="row mt6">
        <div class="col-6">
            <img src="{% static 'CV_image.jpg' %}" class="img-fluid" />
        </div>
        <div class="col-6">
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th><span class="oi oi-envelope-closed"></span> {{ cv.email }}</th>
                </tr>
                <tr>
                    <th><span class="oi oi-location"></span> {{ cv.location }}</th>
                </tr>
                <tr>
                    <th><span class="oi oi-wrench"></span> {{ cv.get_category_display }}</th>
                </tr>
                <tr>
                    <th><span class="oi oi-document"></span> <a href="{% static 'CV.cv_file' %}">Télécharger son CV </a></th>
                </tr>
                <tr>
                    <th><span class="oi oi-clock"></span> Membre depuis le {{ cv.pretty_date }}</th>
                </tr>
                </thead>
            </table>


            <br>
            <h3>Description:</h3>
            <p> {{ cv.description }} </p>
            <br>

        </div>
    </div>


    <hr width="80%">

    <h3>Postes associés ({{ jobs_count }}):</h3>

    <div class="row">
      {% for job in jobs %}
      <div class="card border-warning col-sm-6 col-md-4 col-lg-3 job-card">
        <img src="{% static 'hotel_staff.jpg' %}" class="card-img-top" onclick="window.location='{% url 'detail' job.id %}';" style="cursor: pointer;">
        <div class="card-body pb0">
          <h5 class="card-title" onclick="window.location='{% url 'detail' job.id %}';" style="cursor: pointer;">{{ job.title }}</h5>
          <h5>{{ job.company }}</h5>
          <hr width="90%">
          <p class="card-text pt0"><small>{{ job.summary_of_description }}</small></p>
        </div>
        <div class="card-footer border-warning bt0">
            <table class="table table-bordered">
                    <tbody>
                    <tr>
                        <th><small>{{ job.salary }}DA</small> </th>
                        <th><small>{{ job.get_category_display }}</small></th>
                        <th><small>{{ job.get_contract_type_display }}</small></th>
                    </tr>
                    </tbody>
                </table>
        </div>
      </div>
      {% endfor %}
    </div>



{% endblock %}

jobs/templates/jobs/favorites.html
{% extends 'base.html' %}

{% block content %}

<h2>My favorite jobs:</h2>

<div class="row">
  {% for job in jobs %}
  <div class="card border-warning col-sm-12 col-md-6 col-lg-4">
    <img src="{{ job.image }}" class="card-img-top" onclick="window.location='{% url 'detail' job.id %}';" style="cursor: pointer;">
    <div class="card-body pb0">
      <h5 class="card-title" onclick="window.location='{% url 'detail' job.id %}';" style="cursor: pointer;">{{ job.title }}</h5>
      <hr width="90%">
      <p class="card-text pt0"><small>{{ job.summary_of_summary }}</small></p>
    </div>
    <div class="card-footer border-warning bt0">
      <span><span class="oi oi-clock"></span> {{ job.ready_in_minutes }}min / </span>
      <span> {{ job.price_per_serving }}$</span>
    </div>
  </div>
  {% endfor %}
</div>





{% endblock %}

jobs/templates/jobs/jobs.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<h4>{{ jobs_count }} offres.</h4>

<div class="jobs">
    <div class="row">
      {% for job in jobs %}
      <div class="card border-warning col-sm-6 col-md-4 col-lg-3 job-card">
        <img src="{% static 'hotel_staff.jpg' %}" class="card-img-top" onclick="window.location='{% url 'detail' job.id %}';" style="cursor: pointer;">
        <div class="card-body pb0">
          <h5 class="card-title" onclick="window.location='{% url 'detail' job.id %}';" style="cursor: pointer;">{{ job.title }}</h5>
          <h5>{{ job.company }}</h5>
          <hr width="90%">
          <p class="card-text pt0"><small>{{ job.summary_of_description }}</small></p>
        </div>
        <div class="card-footer border-warning bt0">
            <table class="table table-bordered">
                    <tbody>
                    <tr>
                        <th><small>{{ job.salary }}DA</small> </th>
                        <th><small>{{ job.get_category_display }}</small></th>
                        <th><small>{{ job.get_contract_type_display }}</small></th>
                    </tr>
                    </tbody>
                </table>
        </div>
      </div>
      {% endfor %}
    </div>
</div>




{% endblock %}

jobs/templates/jobs/show_CVs.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


    <h4>{{ CVs_count }} offres.</h4>


    <div class="row">
        {% for CV in CVs %}
            <div class="card mb-3 col-sm-6 col-md-4 col-lg-4" style="max-width: 540px;">
                <div class="row g-0">
                    <div class="col-md-4" style="align-self: center">
                        <img src="{% static 'CV_image.jpg' %}" onclick="window.location='{% url 'detail_CV' CV.id %}';" style="cursor: pointer;max-width: 100%;">
                    </div>
                    <div class="col-md-8">
                        <div class="card-body">
                            <h5 class="card-title" onclick="window.location='{% url 'detail_CV' CV.id %}';" style="cursor: pointer;">{{ CV.firstname }} {{ CV.lastname }}</h5>
                            <p class="card-text">
                                <span class="oi oi-box"></span> {{ CV.email }} <br>
                                <span class="oi oi-location"></span> {{ CV.location }} <br>
                                <span class="oi oi-wrench"></span> {{ CV.get_category_display }} <br>
                                <span class="oi oi-document"></span> <a href="{% static 'CV.cv_file' %}">Télécharger son CV </a> <br>
                            </p>
                            <p class="card-text"><small class="text-muted">En ligne depuis {{ CV.pretty_date }}</small></p>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>



{% endblock %}